services:
  domarchy:
    build:
      context: .
      dockerfile: Dockerfile
    image: overthinkinglabs/domarchy:latest
    container_name: domarchy
    volumes:
      - ./data:/data
      - ./shared:/shared
      - /run/user/1000/pulse/native:/tmp/pulse.socket
    ports:
      - "5900:5900"
      - "8900:8900"
    environment:
      - DISPLAY=:0
      - MEMORY=8G
      - CPUS=4
      - PULSE_SERVER=unix:/tmp/pulse.socket
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    restart: no
    privileged: true
